sudo: false

branches:
  only:
    - master
    
language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv sync'

addons:
  apt:
    packages:
      - doxygen
      - texlive-base
      - texlive-latex-extra
      - texlive-fonts-extra
      - git

before_script:
  - git clone https://github.com/mosra/m.css.git
  - 'pipenv shell'

script:
  - ./m.css/doxygen/dox2html5.py Doxyfile-mcss

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
