trajectory: "../input/traj/dump-6-320-310.lammpstrj"
variables: "../lua_inputs/iceType/vars.lua"
bulk:
  use: false
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: false
topoTwoDim:
  use: true