trajectory: "../input/traj/dump-240-square.lammpstrj"
variables: "../lua_inputs/iceType/vars.lua"
bulk:
  use: false
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: true
topoTwoDim:
  use: false