trajectory: "../input/traj/mW_cubic.lammpstrj"
bulk:
  use: true
  variables: "../lua_inputs/iceType/vars.lua"
  topologicalNetworkCriterion: false
  bondOrderParameters: true
topoOneDim:
  use: false
  variables: "../lua_inputs/iceType/vars.lua"
topoTwoDim:
  use: false
  variables: "../lua_inputs/iceType/vars.lua"

