trajectory: "../input/traj/nucleation.lammpstrj"
bulk:
  use: true
  variables: "../lua_inputs/iceType/vars.lua"
  topologicalNetworkCriterion: true
  bondOrderParameters: false
topoOneDim:
  use: false
  variables: "../lua_inputs/iceType/vars.lua"
topoTwoDim:
  use: false
  variables: "../lua_inputs/iceType/vars.lua"

