transition:
  use: false
  script: "../lua_inputs/transition_diff.lua"
rdf3D:
  use: false
rdf2D:
  use: false
iceType:
  use: true
  trajectory: "../input/traj/nucleation.lammpstrj"
  variables: "../lua_inputs/iceType/vars.lua"
