trajectory: "/home/amritagos/Git/Github/seams-core/input/traj/exampleTraj.lammpstrj"
variables: "/home/amritagos/Git/Github/seams-core/lua_inputs/iceType/vars.lua"
bulk:
  use: false
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: true
topoTwoDim:
  use: false