file: "/home/haozeke/Git/Github/C++/Forks/structureFactor/lua_inputs/parameter.txt"
transition:
 use: false
 script: "../lua_inputs/transition_diff.lua"
rdf3D:
  use: false
rdf2D:
  use: false
iceType:
  use: true
  trajectory: "/home/haozeke/Git/Github/C++/Forks/structureFactor/input/traj/mW_cubic.lammpstrj"
  variables: "../lua_inputs/iceType/vars.lua"
